---
title: Voeg opmerkingen toe aan je HTML en CSS-code
hero_image: images/banner.png
description: Voeg opmerkingen toe aan je HTML en CSS-code.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Voeg opmerkingen toe aan je HTML en CSS-code
