title: Comment your HTML and CSS code
hero_image: images/banner.png
description: Comment your HTML and CSS code.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Comment your HTML and CSS code
