---
title: Commenter ton code HTML et CSS
hero_image: images/banner.png
description: Commente ton code HTML et CSS.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Commenter ton code HTML et CSS
